version: 2
jobs:
 build:
   parallelism: 1
   shell: /bin/bash --login
   environment:
     - CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
     - CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
     - DOCKER_VERSION: 17.05.0-ce
     - DOCKER_COMPOSE_VERSION: 1.15.0
     - METEOR_ALLOW_SUPERUSER: true
     - TOOL_NODE_FLAGS: "--max-old-space-size=4096"
   machine:
     image: ubuntu-1604:202004-01
   steps:
   - checkout
   - run: sudo mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS
   - run:
       command: curl -sSL https://s3.amazonaws.com/circle-downloads/install-circleci-docker.sh | bash -s -- 1.10.0
   - run:
         name: Build docker compose
         command: |
            docker-compose build

   - run:
         name: run docker compose
         command: |
            docker-compose up -d
   - run:
       command: |-
         printf '127.0.0.1       dev.example.com
         ' | sudo tee -a /etc/hosts
   - restore_cache:
       keys:
       # This branch if available
       - v1-dep-{{ .Branch }}-
       # Default branch if not
       - v1-dep-develop-
       # Any branch if there are none on the default branch - this should be unnecessary if you have your default branch configured correctly
       - v1-dep-
   - run: sudo mkdir -p ~/docker
   - run: docker info
   # Save dependency cache
   - save_cache:
       key: v1-dep-{{ .Branch }}-{{ epoch }}
       paths:
       - ~/docker
   - store_test_results:
       path: /tmp/circleci-test-results
   # Save artifacts
   - store_artifacts:
       path: /tmp/circleci-artifacts
   - store_artifacts:
       path: /tmp/circleci-test-results
   - deploy:
       name: Docker Deployment
       command: |
           ./deploy.sh
